### ISSUE TITLE
KeyError: 'frames' when trying to download some presentations

### ISSUE THREAD

**Issue by gonzalognzl** [Gertje823/prezi2pdf#3]
While trying to download some presentations, I get this error message:

```Traceback (most recent call last):
  File "prezi2pdf.py", line 67, in <module>
    download_presentation(id)
  File "prezi2pdf.py", line 46, in download_presentation
    total = len(data['frames'])
KeyError: 'frames'
```
For instance:
https://prezi.com/p/i4dvbt-cfhdt/introduccion-a-la-archivologia-gestion-documental-2023/

I've seen something similar reported at #2 , but this is `prezi.com/p` actually. 
Thanks for any support!

**Comment by gonzalognzl** [comment]
I've just realized it was the "-" char in the id. 
Created PR #4

**Comment by Gertje823** [comment]
Thanks for the bug report and fix :)
I merged your PR into the main branch
